name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud-go:
    runs-on: ubuntu-latest
    name: Analyze Go Project

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run SonarCloud Scan for Go
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
      with:
        args: >
          -Dsonar.organization=mikolaj-sujka
          -Dsonar.projectKey=mikolaj-sujka_backend-sonar-analyze
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io

  